name: 'MinVer Version'
description: 'Run minver-cli and output the calculated semantic version'
author: 'Lee Williams <lee@example.com>'
branding:
  icon: 'tag'
  color: 'blue'

outputs:
  version:
    description: 'The semantic version as calculated by MinVer.'

runs:
  using: 'composite'
  steps:
    - name: Install MinVer CLI
      shell: bash
      run: |
        dotnet tool install --global minver-cli@6.0.0

    - name: Run MinVer
      id: minver
      shell: bash
      run: |
        version=$(minver)
        echo "version=$version" >> "$GITHUB_OUTPUT"
